### C++异常处理入门，C++ try catch入门

程序的错误大致可以分为三种，分别是语法错误、逻辑错误和运行时错误：
1) 语法错误在编译和链接阶段就能发现
2) 逻辑错误是说我们编写的代码思路有问题，不能够达到最终的目标，这种错误可以通过调试来解决。
3) 运行时错误是指程序在运行期间发生的错误，例如除数为 0、内存分配失败、数组越界、文件不存在等。C++ 异常（Exception）机制就是为解决**运行时错误**而引入的。
异常可以发生在当前的 try 块中，也可以发生在 try 块所调用的某个函数中，或者是所调用的函数又调用了另外的一个函数，这个另外的函数中发生了异常。这些异常，都可以被 try 检测到。
```
#include <iostream>
#include <string>
#include <exception>
using namespace std;
void func(){
    throw "Unknown Exception"; //抛出异常
    cout<<"[1]This statement will not be executed."<<endl;
}
int main(){
    try{
        func();
        cout<<"[2]This statement will not be executed."<<endl;
    }catch(const char* &e){
        cout<<e<<endl;
    }
    return 0;
}
```
### C++异常类型以及多级catch匹配
```
try{
    // 可能抛出异常的语句
}catch(exceptionType variable){
    // 处理异常的语句
}
```
exceptionType是异常类型，它指明了当前的 catch 可以处理什么类型的异常；variable是一个变量，用来接收异常信息。当程序抛出异常时，会创建一份数据，这份数据包含了错误信息，程序员可以根据**这些信息来判断到底出了什么问题，接下来怎么处理**。
exceptionType variable和函数的形参非常类似，当异常发生后，会将异常数据传递给 variable 这个变量，这和**函数传参的过程类似**。
总起来说，catch 和真正的函数调用相比，多了一个**在运行阶段将实参和形参匹配**的过程,如果不匹配就会忽略掉的。
C++ 语言本身以及标准库中的函数抛出的异常，都是 **exception** 类或其子类的异常。也就是说，抛出异常时，会创建一个 exception 类或其子类的对象。
另外需要注意的是，如果不希望 catch 处理异常数据，也可以将 variable 省略掉，也即写作：
```
try{
    // 可能抛出异常的语句
}catch(exceptionType){
    // 处理异常的语句
}
```
#### 多级 catch
```
try{
    //可能抛出异常的语句
}catch (exception_type_1 e){
    //处理异常的语句
}catch (exception_type_2 e){
    //处理异常的语句
}
//其他的catch
catch (exception_type_n e){
    //处理异常的语句
}
```
当异常发生时，程序会按照从上到下的顺序，将异常类型和 catch 所能接收的类型逐个匹配。一旦找到类型匹配的 catch 就停止检索，并将异常交给当前的 catch 处理。如果最终也没有找到匹配的 catch，就只能交给系统处理，**终止程序的运行**。
#### catch 在匹配过程中的类型转换
catch在匹配异常类型的过程中，也会进行**类型转换**，但是这种转换受到了更多的限制，仅能进行
* 向上转型
* const 转换
* 数组或函数指针转换


### C++ throw（抛出异常）
异常必须显式地抛出，才能被检测和捕获到；如果**没有显式的抛出**，即使有异常也检测不到。
语法：
```
throw exceptionData;
```
exceptionData 可以是 int、float、bool 等基本类型，也可以是指针、数组、字符串、结构体、类等聚合类型
#### 一个动态数组的例子

#### throw 用作异常规范
throw 关键字除了可以用在函数体中抛出异常，还可以用在函数头和函数体之间，指明当前函数能够抛出的异常类型，这称为**异常规范（Exception specification）**，有些教程也称为异常指示符或异常列表。请看下面的例子：
`double func (char param) throw (int, char, exception);`
只能抛出异常规范中的异常，如果抛出其他类型的异常，try 将无法捕获，只能终止程序
1. 虚函数中的异常规范
C++ 规定，派生类虚函数的异常规范必须与基类虚函数的异常规范一样严格，或者**更严格**。只有这样，当通过基类指针（或者引用）调用派生类虚函数时，才能保证**不违背**基类成员函数的异常规范。 不能说我父类只能抛int的，而子类int char float的什么都能抛，就没有起到规范的作用了。
2. 异常规范与函数定义和函数声明
C++ 规定，异常规范在函数声明和函数定义中必须**同时指明，并且要严格保持一致**

#### 请抛弃异常规范，不要再使用它
异常规范的初衷是好的，它希望让程序员看到函数的定义或声明后，立马就知道该函数会抛出什么类型的异常，这样程序员就可以使用 try-catch 来捕获了。如果没有异常规范，程序员必须阅读函数源码才能知道函数会抛出什么异常。
不过这有时候也不容易做到。例如，func_outer() 函数可能不会引发异常，但它调用了另外一个函数 func_inner()，这个函数可能会引发异常。再如，您编写的函数调用了老式的库函数，此时不会引发异常，但是库更新以后这个函数却引发了异常。总之，异常规范的初衷实现起来有点困难，所以大家达成的一致意见是，最好不要使用异常规范。
异常规范是 C++98 新增的一项功能，但是后来的 C++11 已经将它**抛弃**了，不再建议使用。


### C++ exception类：C++标准异常的基类
C++语言本身或者标准库抛出的异常都是 exception 的子类，称为**标准异常**（Standard Exception）。
通过下面的语句来捕获所有的标准异常（有个兜底儿的异常）：
```
try{
    //可能抛出异常的语句
}catch(exception &e){
    //处理异常的语句
}
```
之所以使用引用，是**为了提高效率**。如果不使用引用，就要经历一次对象拷贝（要调用拷贝构造函数）的过程。

